import { Fragment, useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { getServiceCategories } from "../../api/serviceCategoriesApi";
import {
  getServiceTypes,
  getServiceTypesPaged,
  createServiceType,
  updateServiceType,
  deleteServiceType,
} from "../../api/serviceTypesApi";
import { useToast } from "../../components/system/ToastProvider";
import useConfirmDialog from "../../components/system/useConfirmDialog";
import { extractApiErrorMessage } from "../../utils/errorMessage";
import "../../../public/assets/css/addModalShared.css";
import "./ServiceTypesPage.css";

const EMPTY_FORM = {
  name: "",
  fieldConfigKey: "",
  categoryId: "",
  parentId: "",
};

const slugifyFieldKey = (value) =>
  (value || "")
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9_-]+/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_+|_+$/g, "");

export default function ServiceTypesPage() {
  const { showSuccess, showError } = useToast();
  const { showConfirm, confirmDialog } = useConfirmDialog();

  const [serviceTypes, setServiceTypes] = useState([]);
  const [allServiceTypes, setAllServiceTypes] = useState([]);
  const [categories, setCategories] = useState([]);
  const [selectedCategoryId, setSelectedCategoryId] = useState(null);
  const [showCreate, setShowCreate] = useState(false);
  const [form, setForm] = useState(EMPTY_FORM);
  const [saving, setSaving] = useState(false);
  const [editingId, setEditingId] = useState(null);
  const [loading, setLoading] = useState(true);
  const [expandedParents, setExpandedParents] = useState({});
  const [fieldKeyAutoGenerated, setFieldKeyAutoGenerated] = useState(true);
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);
  const [totalRows, setTotalRows] = useState(0);
  const [totalPages, setTotalPages] = useState(1);

  useEffect(() => {
    loadCategories();
    loadAllServiceTypes();
  }, []);

  const loadCategories = async () => {
    try {
      const data = await getServiceCategories();
      setCategories(Array.isArray(data) ? data : []);
    } catch (e) {
      console.warn("Failed to load categories", e);
    }
  };

  const loadAllServiceTypes = async () => {
    try {
      const data = await getServiceTypes();
      setAllServiceTypes(Array.isArray(data) ? data : []);
    } catch (e) {
      console.warn("Failed to load all service types", e);
    }
  };

  const loadPagedServiceTypes = async (nextPage = page, nextPageSize = pageSize, categoryId = selectedCategoryId) => {
    setLoading(true);
    try {
      const query = {
        page: Math.max(0, Number(nextPage) - 1),
        size: Number(nextPageSize) || 10,
      };
      if (categoryId) {
        query.categoryId = categoryId;
      }
      const data = await getServiceTypesPaged(query);
      const rows = Array.isArray(data?.content) ? data.content : [];
      setServiceTypes(rows);
      setPage(Number(data?.page ?? nextPage) || nextPage);
      setPageSize(Number(data?.size ?? nextPageSize) || nextPageSize);
      setTotalRows(Number(data?.totalElements ?? rows.length) || 0);
      setTotalPages(Math.max(1, Number(data?.totalPages ?? 1) || 1));
    } catch (e) {
      showError("Failed to load service types");
    } finally {
      setLoading(false);
    }
  };

  const normalize = (value) => (value || "").toString().toLowerCase();

  const sortedParents = useMemo(
    () =>
      allServiceTypes
        .filter((st) => !st.parentId)
        .slice()
        .sort((a, b) => normalize(a.name).localeCompare(normalize(b.name))),
    [allServiceTypes]
  );

  const parentOptions = useMemo(() => {
    if (!form.categoryId) {
      return sortedParents.filter((st) => st.id !== editingId);
    }
    const categoryId = String(form.categoryId);
    return sortedParents.filter((st) => String(st.categoryId) === categoryId && st.id !== editingId);
  }, [editingId, form.categoryId, sortedParents]);

  const resetWizard = (nextForm = EMPTY_FORM) => {
    setForm(nextForm);
    setFieldKeyAutoGenerated(true);
  };

  const handleOpenCreate = () => {
    setEditingId(null);
    resetWizard(EMPTY_FORM);
    setShowCreate(true);
  };

  const handleAddSubType = (parentServiceType) => {
    setEditingId(null);
    resetWizard({
      name: "",
      fieldConfigKey: "",
      categoryId: parentServiceType.categoryId ? String(parentServiceType.categoryId) : "",
      parentId: String(parentServiceType.id),
    });
    setShowCreate(true);
  };

  const handleEdit = (serviceType) => {
    setEditingId(serviceType.id);
    resetWizard({
      name: serviceType.name || "",
      fieldConfigKey: serviceType.fieldConfigKey || "",
      categoryId: serviceType.categoryId ? String(serviceType.categoryId) : "",
      parentId: serviceType.parentId ? String(serviceType.parentId) : "",
    });
    setFieldKeyAutoGenerated(false);
    setShowCreate(true);
  };

  const handleCategoryChange = (value) => {
    setForm((prev) => {
      const next = { ...prev, categoryId: value };
      if (next.parentId) {
        const parent = sortedParents.find((st) => String(st.id) === String(next.parentId));
        if (!parent || String(parent.categoryId) !== String(value)) {
          next.parentId = "";
        }
      }
      return next;
    });
  };

  const handleParentChange = (value) => {
    if (!value) {
      setForm((prev) => ({ ...prev, parentId: "" }));
      return;
    }
    const selected = sortedParents.find((st) => String(st.id) === String(value));
    if (selected) {
      setForm((prev) => ({
        ...prev,
        parentId: String(selected.id),
        categoryId: String(selected.categoryId || prev.categoryId || ""),
      }));
    }
  };

  const handleSave = async () => {
    if (!form.name.trim()) {
      showError("Name required");
      return;
    }
    if (!form.categoryId) {
      showError("Category required");
      return;
    }
    if (!form.fieldConfigKey.trim()) {
      showError("Field config key required");
      return;
    }

    setSaving(true);
    try {
      const payload = {
        name: form.name.trim(),
        fieldConfigKey: form.fieldConfigKey.trim().toLowerCase(),
        categoryId: form.categoryId ? Number(form.categoryId) : null,
        parentId: form.parentId ? Number(form.parentId) : null,
      };

      if (editingId) {
        await updateServiceType(editingId, payload);
        showSuccess("Service Type updated");
      } else {
        await createServiceType(payload);
        showSuccess("Service Type added");
      }

      setShowCreate(false);
      resetWizard(EMPTY_FORM);
      setEditingId(null);
      await Promise.all([
        loadAllServiceTypes(),
        loadPagedServiceTypes(page, pageSize, selectedCategoryId),
      ]);
    } catch (e) {
      showError(extractApiErrorMessage(e, "Failed to save service type"));
    } finally {
      setSaving(false);
    }
  };

  const handleDelete = (serviceType) => {
    showConfirm({
      title: "Delete Service Type",
      message: `Are you sure you want to delete "${serviceType.name}"?`,
      confirmLabel: "Delete",
      cancelLabel: "Cancel",
      onConfirm: async () => {
        try {
          await deleteServiceType(serviceType.id);
          showSuccess("Service Type deleted");
          await Promise.all([
            loadAllServiceTypes(),
            loadPagedServiceTypes(page, pageSize, selectedCategoryId),
          ]);
        } catch (e) {
          showError("Failed to delete");
        }
      },
    });
  };

  const toggleParent = (parentId) => {
    const key = parentId?.toString();
    setExpandedParents((prev) => ({
      ...prev,
      [key]: !prev[key],
    }));
  };

  const getCategoryName = (categoryId) => {
    const cat = categories.find((c) => String(c.id) === String(categoryId));
    return cat ? cat.name : "-";
  };
  useEffect(() => {
    loadPagedServiceTypes(page, pageSize, selectedCategoryId);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [page, pageSize, selectedCategoryId]);

  const wizardTitle = editingId
    ? "Edit Service Type"
    : form.parentId
    ? "Add New Sub Type"
    : "Add New Service Type";
  const clampedPage = Math.min(Math.max(1, page), totalPages);
  const pageOffset = (clampedPage - 1) * pageSize;

  return (
    <div className="container-fluid content">
      {/* Header Block */}
      <div className="card border-0 shadow-sm p-4 mb-4 bg-white" style={{ borderRadius: 12 }}>
        <div className="d-flex align-items-center justify-content-between flex-wrap gap-3">
          <div>
            <h2 className="leads-header-title mb-1" style={{ fontSize: "1.4rem", fontWeight: "700", color: "#0f172a" }}>Service Types</h2>
            <nav aria-label="breadcrumb">
              <ol className="breadcrumb mb-0" style={{ fontSize: "0.85rem" }}>
                <li className="breadcrumb-item">
                  <Link to="/admin-dashboard" className="text-decoration-none text-muted">
                    <i className="ti ti-smart-home" />
                  </Link>
                </li>
                <li className="breadcrumb-item text-muted">Services</li>
                <li className="breadcrumb-item active text-primary" aria-current="page">
                  Service Types
                </li>
              </ol>
            </nav>
          </div>
          <div className="d-flex align-items-center gap-2">
            <button
              className="btn btn-primary d-flex align-items-center gap-2"
              style={{
                backgroundColor: "#3b82f6",
                borderColor: "#3b82f6",
                fontWeight: "600",
                padding: "10px 20px",
                borderRadius: "10px",
                fontSize: "0.9rem"
              }}
              onClick={handleOpenCreate}
            >
              <i className="ti ti-plus" style={{ fontSize: "1.1rem" }} />
              Add Service Type
            </button>
          </div>
        </div>
      </div>

      {categories.length > 0 && (
        <ul className="nav nav-tabs mb-4 border-bottom-0 gap-2 flex-wrap">
          <li className="nav-item">
            <button
              type="button"
              className={`nav-link px-4 py-2 border-0 ${selectedCategoryId === null ? "active text-primary fw-bold bg-light" : "text-muted"}`}
              style={{ borderRadius: 10, fontSize: "0.9rem", cursor: "pointer" }}
              onClick={() => {
                setSelectedCategoryId(null);
                setPage(1);
              }}
            >
              All Categories
            </button>
          </li>
          {categories.map((cat) => (
            <li className="nav-item" key={cat.id}>
              <button
                type="button"
                className={`nav-link px-4 py-2 border-0 ${String(selectedCategoryId) === String(cat.id) ? "active text-primary fw-bold bg-light" : "text-muted"}`}
                style={{ borderRadius: 10, fontSize: "0.9rem", cursor: "pointer" }}
                onClick={() => {
                  setSelectedCategoryId(cat.id);
                  setPage(1);
                }}
              >
                {cat.name}
              </button>
            </li>
          ))}
        </ul>
      )}

      {/* Main Content Card */}
      <div className="card table-list-card border-0 shadow-sm" style={{ borderRadius: 12 }}>
        <div className="card-body">
          {/* Controls Bar */}
          <div className="leads-controls-bar d-flex flex-wrap align-items-center justify-content-between gap-3 mb-4">
            <div className="d-flex align-items-center gap-2">
              <h5 className="mb-0 fw-bold" style={{ color: "#0f172a", fontSize: "1.1rem" }}>Service Type List</h5>
              <span className="badge bg-primary-subtle text-primary border border-primary-subtle px-2.5 py-1" style={{ borderRadius: 8, fontSize: "0.8rem" }}>
                {totalRows} type{totalRows !== 1 ? "s" : ""}
              </span>
            </div>
          </div>

          <div className="table-responsive leads-table-wrap border-0 shadow-sm mb-4" style={{ borderRadius: 12 }}>
            <table className="table table-hover align-middle leads-table mb-0">
              <thead>
                <tr>
                  <th className="text-muted" style={{ width: "90px", fontWeight: "600", fontSize: "0.85rem" }}>Index</th>
                  <th className="text-muted" style={{ fontWeight: "600", fontSize: "0.85rem" }}>Category</th>
                  <th className="text-muted" style={{ fontWeight: "600", fontSize: "0.85rem" }}>Name</th>
                  <th className="text-muted" style={{ fontWeight: "600", fontSize: "0.85rem" }}>Field Key</th>
                  <th className="text-muted" style={{ width: "110px", fontWeight: "600", fontSize: "0.85rem" }}>Sub Types</th>
                  <th className="text-muted text-end" style={{ width: "160px", fontWeight: "600", fontSize: "0.85rem" }}>Actions</th>
                </tr>
              </thead>
              <tbody>
                {loading ? (
                  <tr>
                    <td colSpan="6" className="text-center text-muted py-4">
                      Loading...
                    </td>
                  </tr>
                ) : serviceTypes.length > 0 ? (
                  serviceTypes.map((serviceType, parentIndex) => {
                    const children = Array.isArray(serviceType.children) ? serviceType.children.slice() : [];
                    const isExpanded = expandedParents[serviceType.id?.toString()] ?? false;
                    return (
                      <Fragment key={serviceType.id}>
                        <tr className="service-type-parent-row">
                          <td className="fw-semibold" style={{ color: "#1e293b", fontSize: "0.9rem" }}>{pageOffset + parentIndex + 1}</td>
                          <td className="fw-semibold" style={{ color: "#0f172a", fontSize: "0.9rem" }}>{getCategoryName(serviceType.categoryId)}</td>
                          <td>
                            <button
                              type="button"
                              className="service-type-toggle"
                              onClick={() => toggleParent(serviceType.id)}
                              aria-label={isExpanded ? "Collapse" : "Expand"}
                            >
                              <i className={`ti ${isExpanded ? "ti-chevron-down" : "ti-chevron-right"}`} />
                            </button>
                            <strong style={{ color: "#0f172a", fontSize: "0.9rem" }}>{serviceType.name}</strong>
                          </td>
                          <td>
                            <code>{serviceType.fieldConfigKey || "-"}</code>
                          </td>
                          <td>
                            <span className="service-types-count-badge">{children.length}</span>
                          </td>
                          <td className="text-end">
                            <div className="d-flex justify-content-end gap-2">
                              <button
                                type="button"
                                className="btn btn-sm btn-outline-success d-inline-flex align-items-center justify-content-center"
                                style={{ borderRadius: 8, width: 32, height: 32, padding: 0 }}
                                onClick={() => handleAddSubType(serviceType)}
                                title="Add Sub Type"
                              >
                                <i className="ti ti-plus" />
                              </button>
                              <button
                                type="button"
                                className="btn btn-sm btn-outline-primary d-inline-flex align-items-center justify-content-center"
                                style={{ borderRadius: 8, width: 32, height: 32, padding: 0 }}
                                onClick={() => handleEdit(serviceType)}
                                title="Edit"
                              >
                                <i className="ti ti-edit" />
                              </button>
                              <button
                                type="button"
                                className="btn btn-sm btn-outline-danger d-inline-flex align-items-center justify-content-center"
                                style={{ borderRadius: 8, width: 32, height: 32, padding: 0 }}
                                onClick={() => handleDelete(serviceType)}
                                title="Delete"
                              >
                                <i className="ti ti-trash" />
                              </button>
                            </div>
                          </td>
                        </tr>
                        {isExpanded &&
                          children.map((child, childIndex) => (
                            <tr key={child.id} className="service-type-child-row">
                              <td className="text-muted" style={{ fontSize: "0.85rem" }}>
                                {pageOffset + parentIndex + 1}.{childIndex + 1}
                              </td>
                              <td className="text-muted" style={{ fontSize: "0.85rem" }}>{getCategoryName(child.categoryId)}</td>
                              <td>
                                <span className="service-type-child-label text-muted" style={{ fontSize: "0.85rem" }}>{child.name}</span>
                              </td>
                              <td>
                                <code>{child.fieldConfigKey || "-"}</code>
                              </td>
                              <td></td>
                              <td className="text-end">
                                <div className="d-flex justify-content-end gap-2">
                                  <button
                                    type="button"
                                    className="btn btn-sm btn-outline-primary d-inline-flex align-items-center justify-content-center"
                                    style={{ borderRadius: 8, width: 32, height: 32, padding: 0 }}
                                    onClick={() => handleEdit(child)}
                                    title="Edit"
                                  >
                                    <i className="ti ti-edit" />
                                  </button>
                                  <button
                                    type="button"
                                    className="btn btn-sm btn-outline-danger d-inline-flex align-items-center justify-content-center"
                                    style={{ borderRadius: 8, width: 32, height: 32, padding: 0 }}
                                    onClick={() => handleDelete(child)}
                                    title="Delete"
                                  >
                                    <i className="ti ti-trash" />
                                  </button>
                                </div>
                              </td>
                            </tr>
                          ))}
                      </Fragment>
                    );
                  })
                ) : (
                  <tr>
                    <td colSpan="6" className="text-center text-muted py-4">
                      No service types found
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>

          {totalRows > 0 && (
            <div className="leads-pagination-footer d-flex flex-wrap align-items-center justify-content-between gap-3 pt-3 border-top">
              <span className="entries-info text-muted small">
                Showing {pageOffset + 1} to {Math.min(pageOffset + pageSize, totalRows)} of {totalRows} entries
              </span>

              <div className="pagination-numbers-container d-flex align-items-center gap-1">
                <button
                  type="button"
                  className="btn-pagination-arrow btn btn-sm btn-light border-0 d-flex align-items-center justify-content-center"
                  style={{ width: 32, height: 32, borderRadius: 6 }}
                  onClick={() => setPage((p) => Math.max(1, p - 1))}
                  disabled={loading || clampedPage <= 1}
                >
                  <i className="ti ti-chevron-left" />
                </button>

                <span className="text-muted small px-2">
                  Page {clampedPage} of {totalPages}
                </span>

                <button
                  type="button"
                  className="btn-pagination-arrow btn btn-sm btn-light border-0 d-flex align-items-center justify-content-center"
                  style={{ width: 32, height: 32, borderRadius: 6 }}
                  onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
                  disabled={loading || clampedPage >= totalPages}
                >
                  <i className="ti ti-chevron-right" />
                </button>
              </div>

              <div className="d-flex align-items-center gap-2">
                <span className="text-muted small">Rows per page</span>
                <select
                  className="form-select form-select-sm"
                  style={{ width: 80, borderRadius: 8, height: 36 }}
                  value={pageSize}
                  onChange={(e) => {
                    const next = Number(e.target.value);
                    setPageSize(Number.isFinite(next) && next > 0 ? next : 10);
                    setPage(1);
                  }}
                  disabled={loading}
                >
                  {[10, 25, 50].map((n) => (
                    <option key={n} value={n}>
                      {n}
                    </option>
                  ))}
                </select>
              </div>
            </div>
          )}
        </div>
      </div>

      {showCreate && (
        <>
          <div className="modal fade show" style={{ display: "block", backgroundColor: "rgba(0, 0, 0, 0.5)" }} tabIndex="-1">
            <div className="modal-dialog modal-dialog-centered" style={{ maxWidth: "520px" }}>
              <div className="modal-content border-0 shadow-lg" style={{ borderRadius: 16 }}>
                <div className="modal-header border-0 pb-0">
                  <h5 className="modal-title fw-bold" style={{ color: "#0f172a" }}>
                    {wizardTitle}
                  </h5>
                  <button
                    type="button"
                    className="btn-close"
                    onClick={() => setShowCreate(false)}
                  />
                </div>
                <div className="modal-body p-4 pb-0">
                  <div className="mb-3">
                    <label className="form-label fw-semibold text-muted" style={{ fontSize: "0.85rem" }}>Category</label>
                    <select
                      className="form-select"
                      value={form.categoryId}
                      onChange={(e) => handleCategoryChange(e.target.value)}
                      disabled={Boolean(form.parentId) && !editingId}
                      style={{ borderRadius: 10, height: 42 }}
                    >
                      <option value="">-- Select Category --</option>
                      {categories.map((cat) => (
                        <option key={cat.id} value={cat.id}>
                          {cat.name}
                        </option>
                      ))}
                    </select>
                  </div>

                  {form.parentId && (
                    <div className="mb-3">
                      <label className="form-label fw-semibold text-muted" style={{ fontSize: "0.85rem" }}>Parent Type</label>
                      <select
                        className="form-select"
                        value={form.parentId}
                        onChange={(e) => handleParentChange(e.target.value)}
                        disabled={!editingId}
                        style={{ borderRadius: 10, height: 42 }}
                      >
                        <option value="">Top Level Type</option>
                        {parentOptions.map((parent) => (
                          <option key={parent.id} value={parent.id}>
                            {parent.name}
                          </option>
                        ))}
                      </select>
                    </div>
                  )}

                  <div className="mb-3">
                    <label className="form-label fw-semibold text-muted" style={{ fontSize: "0.85rem" }}>Service Type Name</label>
                    <input
                      type="text"
                      className="form-control"
                      value={form.name}
                      onChange={(e) => {
                        const name = e.target.value;
                        setForm((prev) => {
                          const nextKey =
                            !editingId && fieldKeyAutoGenerated
                              ? slugifyFieldKey(name)
                              : prev.fieldConfigKey;
                          return { ...prev, name, fieldConfigKey: nextKey };
                        });
                      }}
                      placeholder="Enter service type name"
                      style={{ borderRadius: 10, height: 42 }}
                      autoFocus
                    />
                  </div>

                  <div className="mb-3">
                    <label className="form-label fw-semibold text-muted" style={{ fontSize: "0.85rem" }}>Field Config Key</label>
                    <input
                      type="text"
                      className="form-control"
                      value={form.fieldConfigKey}
                      onChange={(e) => {
                        const value = slugifyFieldKey(e.target.value);
                        setFieldKeyAutoGenerated(false);
                        setForm({ ...form, fieldConfigKey: value });
                      }}
                      placeholder="e.g. visiting_card"
                      disabled={Boolean(editingId)}
                      style={{ borderRadius: 10, height: 42 }}
                    />
                    {editingId ? (
                      <small className="text-muted mt-1 d-block" style={{ fontSize: "0.75rem" }}>
                        Field config key is locked after creation so renaming does not change field matching.
                      </small>
                    ) : (
                      <small className="text-muted mt-1 d-block" style={{ fontSize: "0.75rem" }}>
                        Field config key auto-generates from the name and can be edited.
                      </small>
                    )}
                  </div>
                </div>
                <div className="modal-footer border-0 pt-0 p-4">
                  <button
                    type="button"
                    className="btn btn-light px-4 py-2"
                    style={{ borderRadius: 10 }}
                    onClick={() => setShowCreate(false)}
                    disabled={saving}
                  >
                    Cancel
                  </button>
                  <button
                    type="button"
                    className="btn btn-primary px-4 py-2"
                    style={{ borderRadius: 10, backgroundColor: "#3b82f6", borderColor: "#3b82f6" }}
                    onClick={handleSave}
                    disabled={saving}
                  >
                    {saving ? "Saving..." : editingId ? "Update" : "Add"}
                  </button>
                </div>
              </div>
            </div>
          </div>
        </>
      )}

      {confirmDialog}
    </div>
  );
}
