import { Fragment, useEffect, useMemo, useState } from "react";
import { getServiceCategories } from "../../api/serviceCategoriesApi";
import {
  getServiceTypes,
  getServiceTypesPaged,
  createServiceType,
  updateServiceType,
  deleteServiceType,
} from "../../api/serviceTypesApi";
import { useToast } from "../../components/system/ToastProvider";
import useConfirmDialog from "../../components/system/useConfirmDialog";
import { extractApiErrorMessage } from "../../utils/errorMessage";
import "../../../public/assets/css/addModalShared.css";
import "./ServiceTypesPage.css";

const EMPTY_FORM = {
  name: "",
  fieldConfigKey: "",
  categoryId: "",
  parentId: "",
};

const slugifyFieldKey = (value) =>
  (value || "")
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9_-]+/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_+|_+$/g, "");

export default function ServiceTypesPage() {
  const { showSuccess, showError } = useToast();
  const { showConfirm, confirmDialog } = useConfirmDialog();

  const [serviceTypes, setServiceTypes] = useState([]);
  const [allServiceTypes, setAllServiceTypes] = useState([]);
  const [categories, setCategories] = useState([]);
  const [selectedCategoryId, setSelectedCategoryId] = useState(null);
  const [showCreate, setShowCreate] = useState(false);
  const [form, setForm] = useState(EMPTY_FORM);
  const [saving, setSaving] = useState(false);
  const [editingId, setEditingId] = useState(null);
  const [loading, setLoading] = useState(true);
  const [expandedParents, setExpandedParents] = useState({});
  const [fieldKeyAutoGenerated, setFieldKeyAutoGenerated] = useState(true);
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);
  const [totalRows, setTotalRows] = useState(0);
  const [totalPages, setTotalPages] = useState(1);

  useEffect(() => {
    loadCategories();
    loadAllServiceTypes();
  }, []);

  const loadCategories = async () => {
    try {
      const data = await getServiceCategories();
      setCategories(Array.isArray(data) ? data : []);
    } catch (e) {
      console.warn("Failed to load categories", e);
    }
  };

  const loadAllServiceTypes = async () => {
    try {
      const data = await getServiceTypes();
      setAllServiceTypes(Array.isArray(data) ? data : []);
    } catch (e) {
      console.warn("Failed to load all service types", e);
    }
  };

  const loadPagedServiceTypes = async (nextPage = page, nextPageSize = pageSize, categoryId = selectedCategoryId) => {
    setLoading(true);
    try {
      const query = {
        page: Math.max(0, Number(nextPage) - 1),
        size: Number(nextPageSize) || 10,
      };
      if (categoryId) {
        query.categoryId = categoryId;
      }
      const data = await getServiceTypesPaged(query);
      const rows = Array.isArray(data?.content) ? data.content : [];
      setServiceTypes(rows);
      setPage(Number(data?.page ?? nextPage) || nextPage);
      setPageSize(Number(data?.size ?? nextPageSize) || nextPageSize);
      setTotalRows(Number(data?.totalElements ?? rows.length) || 0);
      setTotalPages(Math.max(1, Number(data?.totalPages ?? 1) || 1));
    } catch (e) {
      showError("Failed to load service types");
    } finally {
      setLoading(false);
    }
  };

  const normalize = (value) => (value || "").toString().toLowerCase();

  const sortedParents = useMemo(
    () =>
      allServiceTypes
        .filter((st) => !st.parentId)
        .slice()
        .sort((a, b) => normalize(a.name).localeCompare(normalize(b.name))),
    [allServiceTypes]
  );

  const parentOptions = useMemo(() => {
    if (!form.categoryId) {
      return sortedParents.filter((st) => st.id !== editingId);
    }
    const categoryId = String(form.categoryId);
    return sortedParents.filter((st) => String(st.categoryId) === categoryId && st.id !== editingId);
  }, [editingId, form.categoryId, sortedParents]);

  const resetWizard = (nextForm = EMPTY_FORM) => {
    setForm(nextForm);
    setFieldKeyAutoGenerated(true);
  };

  const handleOpenCreate = () => {
    setEditingId(null);
    resetWizard(EMPTY_FORM);
    setShowCreate(true);
  };

  const handleAddSubType = (parentServiceType) => {
    setEditingId(null);
    resetWizard({
      name: "",
      fieldConfigKey: "",
      categoryId: parentServiceType.categoryId ? String(parentServiceType.categoryId) : "",
      parentId: String(parentServiceType.id),
    });
    setShowCreate(true);
  };

  const handleEdit = (serviceType) => {
    setEditingId(serviceType.id);
    resetWizard({
      name: serviceType.name || "",
      fieldConfigKey: serviceType.fieldConfigKey || "",
      categoryId: serviceType.categoryId ? String(serviceType.categoryId) : "",
      parentId: serviceType.parentId ? String(serviceType.parentId) : "",
    });
    setFieldKeyAutoGenerated(false);
    setShowCreate(true);
  };

  const handleCategoryChange = (value) => {
    setForm((prev) => {
      const next = { ...prev, categoryId: value };
      if (next.parentId) {
        const parent = sortedParents.find((st) => String(st.id) === String(next.parentId));
        if (!parent || String(parent.categoryId) !== String(value)) {
          next.parentId = "";
        }
      }
      return next;
    });
  };

  const handleParentChange = (value) => {
    if (!value) {
      setForm((prev) => ({ ...prev, parentId: "" }));
      return;
    }
    const selected = sortedParents.find((st) => String(st.id) === String(value));
    if (selected) {
      setForm((prev) => ({
        ...prev,
        parentId: String(selected.id),
        categoryId: String(selected.categoryId || prev.categoryId || ""),
      }));
    }
  };

  const handleSave = async () => {
    if (!form.name.trim()) {
      showError("Name required");
      return;
    }
    if (!form.categoryId) {
      showError("Category required");
      return;
    }
    if (!form.fieldConfigKey.trim()) {
      showError("Field config key required");
      return;
    }

    setSaving(true);
    try {
      const payload = {
        name: form.name.trim(),
        fieldConfigKey: form.fieldConfigKey.trim().toLowerCase(),
        categoryId: form.categoryId ? Number(form.categoryId) : null,
        parentId: form.parentId ? Number(form.parentId) : null,
      };

      if (editingId) {
        await updateServiceType(editingId, payload);
        showSuccess("Service Type updated");
      } else {
        await createServiceType(payload);
        showSuccess("Service Type added");
      }

      setShowCreate(false);
      resetWizard(EMPTY_FORM);
      setEditingId(null);
      await Promise.all([
        loadAllServiceTypes(),
        loadPagedServiceTypes(page, pageSize, selectedCategoryId),
      ]);
    } catch (e) {
      showError(extractApiErrorMessage(e, "Failed to save service type"));
    } finally {
      setSaving(false);
    }
  };

  const handleDelete = (serviceType) => {
    showConfirm({
      title: "Delete Service Type",
      message: `Are you sure you want to delete "${serviceType.name}"?`,
      confirmLabel: "Delete",
      cancelLabel: "Cancel",
      onConfirm: async () => {
        try {
          await deleteServiceType(serviceType.id);
          showSuccess("Service Type deleted");
          await Promise.all([
            loadAllServiceTypes(),
            loadPagedServiceTypes(page, pageSize, selectedCategoryId),
          ]);
        } catch (e) {
          showError("Failed to delete");
        }
      },
    });
  };

  const toggleParent = (parentId) => {
    const key = parentId?.toString();
    setExpandedParents((prev) => ({
      ...prev,
      [key]: !prev[key],
    }));
  };

  const getCategoryName = (categoryId) => {
    const cat = categories.find((c) => String(c.id) === String(categoryId));
    return cat ? cat.name : "-";
  };
  useEffect(() => {
    loadPagedServiceTypes(page, pageSize, selectedCategoryId);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [page, pageSize, selectedCategoryId]);

  const wizardTitle = editingId
    ? "Edit Service Type"
    : form.parentId
    ? "Add New Sub Type"
    : "Add New Service Type";
  const clampedPage = Math.min(Math.max(1, page), totalPages);
  const pageOffset = (clampedPage - 1) * pageSize;

  return (
    <div className="content service-types-shell">
      <div className="container-fluid">
        <div className="d-flex justify-content-between align-items-center mb-3">
          <h4 className="mb-0">Service Types</h4>
          <button className="btn btn-primary" onClick={handleOpenCreate}>
            Add Service Type +
          </button>
        </div>

        {categories.length > 0 && (
          <div className="service-types-tab-strip">
            <button
              type="button"
              className={`service-types-tab${selectedCategoryId === null ? " active" : ""}`}
              onClick={() => {
                setSelectedCategoryId(null);
                setPage(1);
              }}
            >
              All Categories
            </button>
            {categories.map((cat) => (
              <button
                key={cat.id}
                type="button"
                className={`service-types-tab${String(selectedCategoryId) === String(cat.id) ? " active" : ""}`}
                onClick={() => {
                  setSelectedCategoryId(cat.id);
                  setPage(1);
                }}
              >
                {cat.name}
              </button>
            ))}
          </div>
        )}

        <div className="card">
          <div className="card-header d-flex justify-content-between align-items-center">
            <h5 className="mb-0">Service Type List</h5>
            <span className="badge bg-primary">
              {totalRows} type{totalRows !== 1 ? "s" : ""}
            </span>
          </div>
          <div className="card-body p-0">
            <div className="d-flex flex-wrap align-items-center justify-content-between gap-2 px-3 py-2 border-bottom">
              <div className="d-flex align-items-center gap-2">
                <span className="text-muted small">Rows per page</span>
                <select
                  className="form-select form-select-sm"
                  style={{ width: 110 }}
                  value={pageSize}
                  onChange={(e) => {
                    const next = Number(e.target.value);
                    setPageSize(Number.isFinite(next) && next > 0 ? next : 10);
                    setPage(1);
                  }}
                  disabled={loading}
                >
                  {[10, 25, 50].map((n) => (
                    <option key={n} value={n}>
                      {n}
                    </option>
                  ))}
                </select>
                <span className="text-muted small">
                  {totalRows === 0
                    ? "0 rows"
                    : `Showing ${pageOffset + 1}-${Math.min(pageOffset + pageSize, totalRows)} of ${totalRows}`}
                </span>
              </div>
              <div className="d-flex align-items-center gap-2">
                <button
                  type="button"
                  className="btn btn-sm btn-light"
                  onClick={() => setPage((p) => Math.max(1, p - 1))}
                  disabled={loading || clampedPage <= 1}
                >
                  Prev
                </button>
                <span className="text-muted small">
                  Page {clampedPage} of {totalPages}
                </span>
                <button
                  type="button"
                  className="btn btn-sm btn-light"
                  onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
                  disabled={loading || clampedPage >= totalPages}
                >
                  Next
                </button>
              </div>
            </div>
            <div className="service-types-table-wrap table-responsive">
              <table className="table table-striped table-hover mb-0">
                <thead>
                  <tr>
                    <th style={{ width: "90px" }}>Index</th>
                    <th>Category</th>
                    <th>Name</th>
                    <th>Field Key</th>
                    <th style={{ width: "110px" }}>Sub Types</th>
                    <th style={{ width: "140px" }}>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {loading ? (
                    <tr>
                      <td colSpan="6" className="text-center text-muted py-4">
                        Loading...
                      </td>
                    </tr>
                  ) : serviceTypes.length > 0 ? (
                    serviceTypes.map((serviceType, parentIndex) => {
                      const children = Array.isArray(serviceType.children) ? serviceType.children.slice() : [];
                      const isExpanded = expandedParents[serviceType.id?.toString()] ?? false;
                      return (
                        <Fragment key={serviceType.id}>
                          <tr className="service-type-parent-row">
                            <td>{pageOffset + parentIndex + 1}</td>
                            <td>{getCategoryName(serviceType.categoryId)}</td>
                            <td>
                              <button
                                type="button"
                                className="service-type-toggle"
                                onClick={() => toggleParent(serviceType.id)}
                                aria-label={isExpanded ? "Collapse" : "Expand"}
                              >
                                <i className={`ti ${isExpanded ? "ti-chevron-down" : "ti-chevron-right"}`} />
                              </button>
                              <strong>{serviceType.name}</strong>
                            </td>
                            <td>
                              <code>{serviceType.fieldConfigKey || "-"}</code>
                            </td>
                            <td>
                              <span className="service-types-count-badge">{children.length}</span>
                            </td>
                            <td>
                              <div className="d-inline-flex align-items-center gap-2">
                                <button
                                  type="button"
                                  className="btn btn-sm btn-success d-inline-flex align-items-center justify-content-center"
                                  onClick={() => handleAddSubType(serviceType)}
                                  title="Add Sub Type"
                                  style={{ width: 32, height: 32, padding: 0 }}
                                >
                                  <i className="ti ti-plus" />
                                </button>
                                <button
                                  type="button"
                                  className="btn btn-sm btn-primary d-inline-flex align-items-center justify-content-center"
                                  onClick={() => handleEdit(serviceType)}
                                  title="Edit"
                                  style={{ width: 32, height: 32, padding: 0 }}
                                >
                                  <i className="ti ti-edit" />
                                </button>
                                <button
                                  type="button"
                                  className="btn btn-sm btn-danger d-inline-flex align-items-center justify-content-center"
                                  onClick={() => handleDelete(serviceType)}
                                  title="Delete"
                                  style={{ width: 32, height: 32, padding: 0 }}
                                >
                                  <i className="ti ti-trash" />
                                </button>
                              </div>
                            </td>
                          </tr>
                          {isExpanded &&
                            children.map((child, childIndex) => (
                              <tr key={child.id} className="service-type-child-row">
                                <td>
                                  {pageOffset + parentIndex + 1}.{childIndex + 1}
                                </td>
                                <td>{getCategoryName(child.categoryId)}</td>
                                <td>
                                  <span className="service-type-child-label">{child.name}</span>
                                </td>
                                <td>
                                  <code>{child.fieldConfigKey || "-"}</code>
                                </td>
                                <td></td>
                                <td>
                                  <div className="d-inline-flex align-items-center gap-2">
                                    <button
                                      type="button"
                                      className="btn btn-sm btn-primary d-inline-flex align-items-center justify-content-center"
                                      onClick={() => handleEdit(child)}
                                      title="Edit"
                                      style={{ width: 32, height: 32, padding: 0 }}
                                    >
                                      <i className="ti ti-edit" />
                                    </button>
                                    <button
                                      type="button"
                                      className="btn btn-sm btn-danger d-inline-flex align-items-center justify-content-center"
                                      onClick={() => handleDelete(child)}
                                      title="Delete"
                                      style={{ width: 32, height: 32, padding: 0 }}
                                    >
                                      <i className="ti ti-trash" />
                                    </button>
                                  </div>
                                </td>
                              </tr>
                            ))}
                        </Fragment>
                      );
                    })
                  ) : (
                    <tr>
                      <td colSpan="6" className="text-center text-muted py-4">
                        No service types found
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>

      {showCreate && (
        <>
          <div className="avm-backdrop" role="presentation">
            <div
              className="avm-modal"
              style={{ maxWidth: "640px" }}
              onClick={(e) => e.stopPropagation()}
              role="dialog"
              aria-modal="true"
            >
              <div className="avm-modal-header">
                <h2 className="avm-modal-title">{wizardTitle}</h2>
                <button
                  type="button"
                  className="avm-modal-close"
                  onClick={() => setShowCreate(false)}
                  aria-label="Close"
                >
                  X
                </button>
              </div>

              <div className="avm-body">
                <div className="avm-grid">
                  <div className="avm-field">
                    <label className="avm-label">Category</label>
                    <select
                      className="avm-select"
                      value={form.categoryId}
                      onChange={(e) => handleCategoryChange(e.target.value)}
                      disabled={Boolean(form.parentId) && !editingId}
                    >
                      <option value="">-- Select Category --</option>
                      {categories.map((cat) => (
                        <option key={cat.id} value={cat.id}>
                          {cat.name}
                        </option>
                      ))}
                    </select>
                  </div>

                  {form.parentId && (
                    <div className="avm-field">
                      <label className="avm-label">Parent Type</label>
                      <select
                        className="avm-select"
                        value={form.parentId}
                        onChange={(e) => handleParentChange(e.target.value)}
                        disabled={!editingId}
                      >
                        <option value="">Top Level Type</option>
                        {parentOptions.map((parent) => (
                          <option key={parent.id} value={parent.id}>
                            {parent.name}
                          </option>
                        ))}
                      </select>
                    </div>
                  )}

                  <div className="avm-field full">
                    <label className="avm-label">Service Type Name</label>
                    <input
                      type="text"
                      className="avm-input"
                      value={form.name}
                      onChange={(e) => {
                        const name = e.target.value;
                        setForm((prev) => {
                          const nextKey =
                            !editingId && fieldKeyAutoGenerated
                              ? slugifyFieldKey(name)
                              : prev.fieldConfigKey;
                          return { ...prev, name, fieldConfigKey: nextKey };
                        });
                      }}
                      placeholder="Enter service type name"
                      autoFocus
                    />
                  </div>

                  <div className="avm-field full">
                    <label className="avm-label">Field Config Key</label>
                    <input
                      type="text"
                      className="avm-input"
                      value={form.fieldConfigKey}
                      onChange={(e) => {
                        const value = slugifyFieldKey(e.target.value);
                        setFieldKeyAutoGenerated(false);
                        setForm({ ...form, fieldConfigKey: value });
                      }}
                      placeholder="e.g. visiting_card"
                      disabled={Boolean(editingId)}
                    />
                    {editingId && (
                      <small className="text-muted">
                        Field config key is locked after creation so renaming does not change field matching.
                      </small>
                    )}
                  </div>
                </div>
              </div>

              <div className="avm-footer">
                <div className="text-muted small">Field config key auto-generates from the name and can be edited.</div>
                <div className="avm-footer-right">
                  <button
                    type="button"
                    className="avm-btn light"
                    onClick={() => setShowCreate(false)}
                    disabled={saving}
                  >
                    Cancel
                  </button>
                  <button
                    type="button"
                    className="avm-btn primary"
                    onClick={handleSave}
                    disabled={saving}
                  >
                    {saving ? "Saving..." : editingId ? "Update" : "Add"}
                  </button>
                </div>
              </div>
            </div>
          </div>
        </>
      )}

      {confirmDialog}
    </div>
  );
}
