ALTER TABLE leads
    ADD COLUMN IF NOT EXISTS lead_country VARCHAR(10),
    ADD COLUMN IF NOT EXISTS lead_state   VARCHAR(10),
    ADD COLUMN IF NOT EXISTS lead_city    VARCHAR(200),
    ADD COLUMN IF NOT EXISTS project_id   BIGINT;
