CREATE TABLE quotation_template (
    id                  BIGSERIAL PRIMARY KEY,
    company_name        VARCHAR(200),
    company_tagline     VARCHAR(300),
    address             TEXT,
    phone1              VARCHAR(30),
    phone2              VARCHAR(30),
    work_phone          VARCHAR(30),
    email               VARCHAR(200),
    website             VARCHAR(200),
    gstin               VARCHAR(20),
    state_code          VARCHAR(10),
    state_name          VARCHAR(100),
    udyam_number        VARCHAR(50),
    logo_base64         TEXT,
    signature_base64    TEXT,
    bank_name           VARCHAR(200),
    account_number      VARCHAR(30),
    ifsc_code           VARCHAR(20),
    branch              VARCHAR(200),
    validity_days       INT DEFAULT 30,
    prepared_by_default VARCHAR(200),
    approved_by_default VARCHAR(200),
    policy_text         TEXT,
    created_at          TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP NOT NULL DEFAULT NOW()
);
