ALTER TABLE email_templates
ADD COLUMN IF NOT EXISTS is_builtin BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE email_templates
SET is_builtin = TRUE
WHERE template_key IN ('OFFER_LETTER_TEMPLATE', 'PROFILE_COMPLETION_TEMPLATE');
