CREATE TABLE campaign_leads (
    id BIGSERIAL PRIMARY KEY,
    lead_id VARCHAR(64) NOT NULL UNIQUE,
    created_time VARCHAR(64),
    ad_id VARCHAR(64),
    ad_name VARCHAR(255),
    adset_id VARCHAR(64),
    adset_name VARCHAR(255),
    campaign_id VARCHAR(64),
    campaign_name VARCHAR(255),
    form_id VARCHAR(64),
    form_name VARCHAR(255),
    is_organic VARCHAR(20),
    platform VARCHAR(50),
    moq VARCHAR(255),
    industry VARCHAR(255),
    email VARCHAR(190),
    full_name VARCHAR(200),
    phone VARCHAR(40),
    city VARCHAR(100),
    lead_status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
